#Tokenization

In [2]:
dummy = "I love learning NLP. Text preprocessing is very useful. Tokenization splits text into smaller parts. Python makes NLP easy."

In [3]:
dummy

'I love learning NLP. Text preprocessing is very useful. Tokenization splits text into smaller parts. Python makes NLP easy.'

In [4]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [5]:
#sentence Tokenization
import nltk
nltk.download('punkt_tab')

sents = sent_tokenize(dummy)
sents

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

['I love learning NLP.',
 'Text preprocessing is very useful.',
 'Tokenization splits text into smaller parts.',
 'Python makes NLP easy.']

In [6]:
#Word Tokenization
for sent in sents:
  print(word_tokenize(sent))

['I', 'love', 'learning', 'NLP', '.']
['Text', 'preprocessing', 'is', 'very', 'useful', '.']
['Tokenization', 'splits', 'text', 'into', 'smaller', 'parts', '.']
['Python', 'makes', 'NLP', 'easy', '.']

#Dataset Load IMDB 50k movie Review

In [7]:
import pandas as pd

df = pd.read_csv("IMDB Dataset.csv")
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [8]:
df.shape

(50000, 2)

In [9]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

#2. Lowercasing

In [10]:
print(df['review'].iloc[1].lower())

a wonderful little production. <br /><br />the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master's of comedy and his life. <br /><br />the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell's murals decorating every surface) are terribly well done.

In [11]:
#Complete Dataset Convert Lowercase
df['review'] = df['review'].str.lower()
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

#3. Remove HTML Tags

In [12]:
import re
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'', text)

In [13]:
text = """<htm><body><p> Movie 1</p><p> Actor - Aamir Khan</p><p> click here to <a href="https://www.google.com/">download</a></p><body><html> """
remove_html_tags(text)

' Movie 1 Actor - Aamir Khan click here to download '

In [14]:
df['review'].apply(remove_html_tags)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

#4. Remove URLs

In [15]:
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'', text)

In [16]:
text1 = "Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb"
text2 = "Check out my notebook http://www.kaggle.com/campusx/notebook8223fc1abb"
text3 = "Google search here www.google.com"
text4 = "For notebook click https://www.kaggle.com/campusx/notebook8223fc1abb to search check www.google.com"

In [17]:
remove_url(text2)

'Check out my notebook '

#5. Remove Punctuation

In [18]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [19]:
exclude = string.punctuation

In [20]:
def remove_punc(text):
  for char in exclude:
    text = text.replace(char,'')
  return text

In [21]:
text = "string. With. Punctuation?"
text

'string. With. Punctuation?'

In [22]:
import time
import string

exclude = string.punctuation
start = time.time()
print(remove_punc(text))
time1 = time.time() - start
print(time1*50000)

string With Punctuation
21.409988403320312

In [23]:
#Always Uses Large Datasets
def remove_punc1(text):
  return text.translate(str.maketrans('', '', exclude))

In [24]:
start = time.time()
remove_punc1(text)
time2 = time.time() - start
print(time2*50000)
time1/time2

5.948543548583984

3.599198396793587

#6. Chat Word Treatment

In [25]:

chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ASL": "Age, Sex, Location",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can't Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don't Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "PITA": "Pain In The A**",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "STATS": "Your Sex And Age",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn't Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait...",
    "WB": "Welcome Back",
    "WTF": "What The F**k",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "WYD": "What You Doing?",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired"
}

In [26]:
print(chat_words["LOL"])
print(chat_words["BRB"])
print(chat_words["ASAP"])

Laughing Out Loud
Be Right Back
As Soon As Possible

In [27]:
def chat_conversion(text):
  new_text = []
  for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)
  return " ".join(new_text)

In [28]:
chat_conversion("one minute BRB")

'one minute Be Right Back'

In [29]:
chat_conversion("IMHO he is the best")

'In My Honest/Humble Opinion he is the best'

# 7. Removing Stopwords

In [30]:
from nltk.corpus import stopwords

In [31]:
import nltk
nltk.download('stopwords')

stopwords.words("english")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [32]:
def remove_stopwords(text):
  new_text = []

  for word in text.split():
    if word in stopwords.words('english'):
      new_text.append('')
    else:
      new_text.append(word)
  x = new_text[:]
  new_text.clear()
  return" ".join(x)

In [33]:
remove_stopwords(" Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause")

'Probably  all-time favorite movie,  story  selflessness, sacrifice  dedication   noble cause'

In [34]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [35]:
df['review'].apply(remove_stopwords)

0        one    reviewers  mentioned   watching  1 oz e...
1         wonderful little production. <br /><br />the ...
2         thought    wonderful way  spend time    hot s...
3        basically there's  family   little boy (jake) ...
4        petter mattei's "love   time  money"   visuall...
                               ...
49995     thought  movie    right good job.    creative...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997       catholic taught  parochial elementary schoo...
49998     going    disagree   previous comment  side  m...
49999     one expects  star trek movies   high art,   f...
Name: review, Length: 50000, dtype: object

#Handling Emojis

In [36]:

import re

def remove_emoji(text):
  emoji_pattern = re.compile("["
                               "\U0001F300-\U0001F5FF"
                               "\U0001F600-\U0001F64F"
                               "\U0001F680-\U0001F6FF"
                               "\U0001F900-\U0001F9FF"
                               "\U0001FA70-\U0001FAFF"
                               "\U00002600-\U000026FF"
                               "\U00002700-\U000027BF"
                               "]+",flags=re.UNICODE)
  return emoji_pattern.sub(r" ", text)

In [37]:
remove_emoji(text = "Hello 😍 Python 🚀🔥 NLP 😊")

'Hello   Python   NLP  '

In [38]:
!pip install emoji
import emoji
print(emoji.demojize("Python is 🔥"))

Collecting emoji
  Downloading emoji-2.16.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.16.0-py3-none-any.whl (610 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 610.9/610.9 kB 11.1 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.16.0
Python is :fire:

In [39]:
import emoji
print(emoji.demojize("loved the movie. it was 😘"))

loved the movie. it was :face_blowing_a_kiss:

#Tokenization
(1) Using the split function

In [40]:
#Word Tokenization
sent1 = "I am going to delhi"
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [41]:
#Sentence Tokenization
sent2 = "I am going to delhi. I will stay there for 3 days. Let's hope the trip to be great"
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [42]:
#problem with split function
sent3 = "I am going to delhi!"
print(sent3.split())

sent4 = "Where do think i should go? i have 3 day holiday"
sent4.split('.')

['I', 'am', 'going', 'to', 'delhi!']

['Where do think i should go? i have 3 day holiday']

2. Regular Expression

In [43]:
import re
sent3 = "I am going to delhi!"
tokens = re.findall("[\w']+", sent3)
tokens

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_590/4184121535.py:3: SyntaxWarning: invalid escape sequence '\w'
  tokens = re.findall("[\w']+", sent3)

['I', 'am', 'going', 'to', 'delhi']

In [44]:
sent4 = "Where do think, i should go? i have 3! day holiday"
sentences = re.compile('[.?!]').split(sent4)
sentences

['Where do think, i should go', ' i have 3', ' day holiday']

3. NLTK

In [45]:
from nltk import word_tokenize,sent_tokenize

In [46]:
sent1 = "I am going to delhi!"
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'delhi', '!']

In [47]:
text = "Where do think, i should go? i have 3! day holiday"
sent_tokenize(text)

['Where do think, i should go?', 'i have 3!', 'day holiday']

4. Spacy

In [48]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [49]:
docs1 = nlp(sent1)

for token in docs1:
  print(token)

I
am
going
to
delhi
!

#Stemming

In [50]:
from nltk.stem import PorterStemmer

In [51]:
ps = PorterStemmer()
def stem_words(text):
  return" ".join([ps.stem(word) for word in text.split()])

In [52]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [53]:
text = (" Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause")
text

' Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause'

In [54]:
stem_words(text)

'probabl my all-tim favorit movie, a stori of selflessness, sacrific and dedic to a nobl caus'

#Lemmatizer

In [1]:
import nltk
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

In [55]:
sentence = "He was running and eating at same time"
punctuation = "?:.,;"

In [56]:
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
  if word in punctuation:
    sentence_words.remove(word)
sentence_words

['He', 'was', 'running', 'and', 'eating', 'at', 'same', 'time']

In [57]:
import nltk
nltk.download('wordnet')

print("{0:20}{1:20}".format("word","lemma"))
for word in sentence_words:
  print("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word)))

[nltk_data] Downloading package wordnet to /root/nltk_data...

word                lemma
He                  He
was                 wa
running             running
and                 and
eating              eating
at                  at
same                same
time                time